"""Build the Grafana dashboard JSON from PANELS."""
from __future__ import annotations
import json
from typing import Any

from grafana_ailedger.panels import PANELS, Panel, DATASOURCE_UID


DASHBOARD_UID = "ailedger-business-pulse"
DASHBOARD_TITLE = "AILedger — Business Pulse"


def _ds() -> dict[str, str]:
    return {"type": "grafana-postgresql-datasource", "uid": DATASOURCE_UID}


def _stat_field_config(p: Panel) -> dict[str, Any]:
    defaults: dict[str, Any] = {"unit": p.unit}
    if p.decimals is not None:
        defaults["decimals"] = p.decimals
    if p.thresholds:
        defaults["thresholds"] = {"mode": "absolute", "steps": list(p.thresholds)}
        defaults["color"] = {"mode": "thresholds"}
    return {"defaults": defaults, "overrides": []}


def _stat_options() -> dict[str, Any]:
    return {
        "reduceOptions": {"calcs": ["last"], "fields": "", "values": False},
        "textMode": "value",
        "colorMode": "value",
        "graphMode": "area",
    }


def _timeseries_field_config(p: Panel) -> dict[str, Any]:
    return {
        "defaults": {
            "unit": p.unit,
            "custom": {
                "drawStyle": "line",
                "lineInterpolation": "smooth",
                "fillOpacity": 15,
                "pointSize": 4,
                "spanNulls": False,
            },
        },
        "overrides": [],
    }


def _timeseries_options() -> dict[str, Any]:
    return {"legend": {"displayMode": "list", "placement": "bottom"}, "tooltip": {"mode": "multi"}}


def _barchart_options() -> dict[str, Any]:
    return {
        "orientation": "horizontal",
        "xTickLabelRotation": 0,
        "showValue": "always",
        "stacking": "none",
        "legend": {"showLegend": False},
    }


def _table_options() -> dict[str, Any]:
    return {"showHeader": True, "footer": {"show": False}}


def _panel_to_json(p: Panel) -> dict[str, Any]:
    panel: dict[str, Any] = {
        "id": p.id,
        "title": p.title,
        "type": p.panel_type,
        "datasource": _ds(),
        "gridPos": p.gridpos,
        "targets": [{
            "refId": "A",
            "datasource": _ds(),
            "rawSql": p.sql,
            "format": p.format,
            "editorMode": "code",
        }],
    }
    if p.description:
        panel["description"] = p.description

    if p.panel_type == "stat":
        panel["fieldConfig"] = _stat_field_config(p)
        panel["options"] = _stat_options()
    elif p.panel_type == "timeseries":
        panel["fieldConfig"] = _timeseries_field_config(p)
        panel["options"] = _timeseries_options()
    elif p.panel_type == "barchart":
        panel["fieldConfig"] = {"defaults": {"unit": p.unit}, "overrides": []}
        panel["options"] = _barchart_options()
    elif p.panel_type == "table":
        panel["fieldConfig"] = {"defaults": {}, "overrides": []}
        panel["options"] = _table_options()
    else:
        panel["fieldConfig"] = {"defaults": {}, "overrides": []}
        panel["options"] = {}

    return panel


def build_dashboard(*, message: str = "Generated by grafana-ailedger") -> dict[str, Any]:
    return {
        "dashboard": {
            "uid": DASHBOARD_UID,
            "title": DASHBOARD_TITLE,
            "tags": ["ailedger", "monitoring", "tier1"],
            "timezone": "browser",
            "schemaVersion": 39,
            "refresh": "30s",
            "time": {"from": "now-24h", "to": "now"},
            "panels": [_panel_to_json(p) for p in PANELS],
            "templating": {"list": []},
            "annotations": {"list": []},
        },
        "folderUid": "",
        "overwrite": True,
        "message": message,
    }


def render() -> str:
    return json.dumps(build_dashboard(), indent=2)


if __name__ == "__main__":
    print(render())
