"""Byte-parity tests for ailedger_cli.canonical against the shared golden corpus.

The corpus (testdata/jcs-golden-vectors.json) is generated by
sdk/test/generate-jcs-vectors.mjs using the production `canonicalize` npm
package — the same code that computes chain hashes in the proxy. Any
divergence here means Python verification would disagree with TypeScript
production hashing.
"""

from __future__ import annotations

import json
import math
from pathlib import Path

import pytest

from ailedger_cli.canonical import canonical, canonical_bytes

_CORPUS_PATH = Path(__file__).resolve().parents[2] / "testdata" / "jcs-golden-vectors.json"
_CORPUS = json.loads(_CORPUS_PATH.read_text(encoding="utf-8"))


@pytest.mark.parametrize(
    "vector", _CORPUS["vectors"], ids=[v["name"] for v in _CORPUS["vectors"]]
)
def test_golden_vector_parity(vector: dict) -> None:
    assert canonical(vector["input"]) == vector["expected"]


def test_utf16_key_order_beats_codepoint_order() -> None:
    # U+10000 (𐀀) is one code point above U+FF61 but sorts FIRST in UTF-16
    # code units (D800 DC00 < FF61). A code-point sort gets this backwards.
    out = canonical({"｡": 1, "\U00010000": 2})
    assert out == '{"\U00010000":2,"｡":1}'


def test_negative_zero_serializes_as_zero() -> None:
    assert canonical(-0.0) == "0"


def test_es_number_formatting_edges() -> None:
    assert canonical(100.0) == "100"
    assert canonical(1e-7) == "1e-7"
    assert canonical(1e21) == "1e+21"
    assert canonical(1e20) == "100000000000000000000"
    assert canonical(0.000001) == "0.000001"
    assert canonical(5e-324) == "5e-324"
    assert canonical(10 ** 22) == "1e+22"


def test_rejects_non_finite() -> None:
    with pytest.raises(ValueError):
        canonical(math.nan)
    with pytest.raises(ValueError):
        canonical(math.inf)


def test_rejects_non_string_keys_and_unknown_types() -> None:
    with pytest.raises(TypeError):
        canonical({1: "x"})
    with pytest.raises(TypeError):
        canonical({"x": object()})


def test_canonical_bytes_is_utf8() -> None:
    assert canonical_bytes({"€": 1}) == '{"€":1}'.encode()
